Name            = "Wordpress"
Env             = "Dev"
Created_by      = "Vova"
Dept            = "IT"
ami             = "ami-00068cd7555f543d5"
instance_type   = "t2.micro"
key_name        = "vova_mac"
count           = "2"